export enum Errors {
  INVALID_EMAIL = 'Invalid email',
  INVALID_PASSWORD = 'Invalid password',
  INVALID_USERNAME = 'Invalid username',
  INVALID_NAME = 'Invalid name',
  INVALID_CREDENTIALS = 'Invalid credentials',
  REQUIRED_TOKEN = 'Token is required',
  REQUIRED_EMAIL = 'Email is required',
  REQUIRED_REFRESH_TOKEN = 'Refresh token is required',
  REQUIRED_PASSWORD = 'Password is required',
  REQUIRED_USERNAME = 'Username is required',
  REQUIRED_ID = 'User ID is required',
  NOT_FOUND_WORD = "Today's Word not found",
  NOT_FOUND_USER = 'User not found',
  NOT_FOUND_DOCUMENT = "Document not found",
  UNAUTHORIZED = 'Unauthorized',
  INVALID_TOKEN = 'Invalid token',
  TOKEN_EXPIRED = 'Expired Token',
  NO_TOKEN = 'No token provided',
  NOT_FOUND = 'Not found',
  SERVER_ERROR = 'Internal Server error',
  INCORRECT_ATTEMPT = 'The attempt is incorrect',
  CORRECT_ATTEMPT = 'The attempt is correct',
  ALREADY_GOT_RIGHT = "You have already correct today's word",
  ALREADY_FAILED = "You have already used all attempts"
}